# Generated by Django 3.2.12 on 2022-04-01 11:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('racks', '0001_initial'),
        ('books', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=255)),
                ('purchased_on', models.DateField()),
                ('published_on', models.DateField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_items', to='books.book')),
                ('loaned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loaned_book_items', to='students.student')),
                ('rack', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='book_items', to='racks.rack')),
                ('reserved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reserved_book_items', to='students.student')),
            ],
        ),
    ]
