# Generated by Django 3.2.12 on 2022-03-22 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        ('book_items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='loaned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='loaned_book_items', to='students.student'),
        ),
        migrations.AddField(
            model_name='bookitem',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reserved_book_items', to='students.student'),
        ),
    ]
