# Generated by Django 3.2.12 on 2022-03-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='published_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='purchased_on',
            field=models.DateField(),
        ),
    ]
