# Generated by Django 3.2.12 on 2022-03-17 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('paid', models.BooleanField(blank=True, default=False, null=True)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='fines', to='students.student')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='transactions.transaction')),
            ],
        ),
    ]
