# Generated by Django 4.0.2 on 2022-03-04 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
