# Generated by Django 4.0.2 on 2022-03-04 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_alter_fine_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
