# Generated by Django 3.2.12 on 2022-03-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fines', '0002_auto_20220319_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
