# Generated by Django 3.2.12 on 2022-04-01 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('floor', models.IntegerField()),
                ('segment', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('rack_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
