# Generated by Django 3.2.12 on 2022-03-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('segment', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('rack_number', models.IntegerField()),
            ],
        ),
    ]
