# Generated by Django 3.2.12 on 2022-04-01 09:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('book_items', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issued_at', models.DateField(auto_now_add=True)),
                ('overdue', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('returned', models.BooleanField(default=False)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('book_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='book_items.bookitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='students.student')),
            ],
        ),
    ]
