# Generated by Django 4.0.2 on 2022-03-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
