# Generated by Django 4.0.2 on 2022-03-01 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0002_alter_transaction_issued_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='issued_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to=settings.AUTH_USER_MODEL),
        ),
    ]
